server {
    listen 80;
    root /usr/share/nginx/html;

    error_page 503 /loading.html;

    location = /loading.html {
        internal;
        add_header Cache-Control "no-store" always;
    }

    location / {
        return 503;
    }
}
